### PR TITLE
Update jets3t

### PR DESCRIPTION
**Pull request by logarithm**

### CODE REVIEW

**Review by drcrallen — CHANGES_REQUESTED** [review]
This is not right. The jets3t version is set by the hadoop profile

**Comment by drcrallen** [comment]
For example, https://github.com/metamx/spark/blob/v2.1.0-mmx/pom.xml#L2556 sets 9.3. That is where it should be updated, probably for all the versions of hadoop

**Comment by isimonenko** [comment]
let me pick up on that.

**Review by drcrallen — APPROVED** [review]

**Comment by drcrallen** [comment]
waiting for @jisookim0513 to merge

**Comment by jisookim0513** [comment]
What is this update on jets3t for? Also, could you add the commit and brief description to README so we know that we made our own change to use newer jets3t version?

**Comment by logarithm** [comment]
For making possible using AWSv4 signature which is only one possible way to communicate with regions which were created after some date in 2014. The full list can be found [here](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region).

**Comment by jisookim0513** [comment]
@logarithm thanks, I merged it but please log this commit to README later.

**Pull request merged**
